version: "3"

services:
  mongodb_provider:
    image: mongo
    container_name: mongodb_provider
    volumes:
      - ./.docker_data/mongodb:/data/db
    ports:
      - 27017:27017
    restart: always

  oauth_provider:
    build: ./oauth_provider
    container_name: oauth_provider
    environment:
      - MONGODB_USERNAME=${MONGODB_USERNAME}
      - MONGODB_PASSWORD=${MONGODB_PASSWORD}
      - SIGNATURE_SECRET=${SIGNATURE_SECRET}
    volumes:
      - ./oauth_provider:/opt/app/oauth_provider
    depends_on:
      - mongodb_provider
    ports:
      - 5002:5002