name: golangci-lint

on:
  push:
    branches: [ main ]
  pull_request:
    branches: '*'
    
permissions:
  contents: read
  
jobs:
  golangci:
    name: lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        working-directory: oauth_provider
      - name: golangci-lint
        uses: golangci/golangci-lint-action@v2
        with:
          version: latest
